service:
  type: LoadBalancer

configMaps:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "ConnectStringTest": "Connection For Test file"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Warning",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "AppSettings": {
        "SettingKey1": "App value From test file"
      }
    }

  cachesettings.json: |
    {
      "CacheConnectionStrings": {
        "ConnectStringTest": "Connection For Test"
    }