image:
  repository: webapidemo
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: "v1.2"

configMaps:
  appsettings.json: |
    {
      "ConnectionStrings": {
        "ConnectStringTest": "Connection For Test file"
      },
      "Logging": {
        "LogLevel": {
          "Default": "Warning",
          "Microsoft.AspNetCore": "Warning"
        }
      },
      "AllowedHosts": "*",
      "AppSettings": {
        "SettingKey1": "App value From test file"
      }
    }

cachesettings.json: |
    {
      "CacheConnectionStrings": {
        "ConnectStringTest": "Connection For Test"
    }