apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-webapi.fullname" . }}
  labels: 
    {{- include "demo-webapi.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMaps | nindent 2 }}